[app]
name = "Fortune Teller"
category = "Badge"

[entry]
class = "FortuneTellerApp"

[metadata]
author = "nightcaster"
license = "LGPL-3.0-only"
url = "https://github.com/nightcaster/Tildagon-FortuneTeller"
description = "Emulates origami fortune tellers with 6 corners, color/number folds, and daily seeded EMF festival fortunes from over 2 million possible combinations."
version = "4"
